### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by RosaEidola** [MageNume/bustabit-bot#2]
Hello again,

On startup it throws the following and just loops:

2020-07-17T18:01:22.955187+00:00 app[web.1]: bot.py:84: DeprecationWarning: use options instead of firefox_options 
2020-07-17T18:01:22.955213+00:00 app[web.1]: self._webdriver = webdriver.Firefox(firefox_profile=profile_folder, firefox_options=opt) 
2020-07-17T18:01:22.955219+00:00 app[web.1]: Are you sure you are logged with your profile ?

**Comment by KylianCadet** [comment]
Did you logged in your butsabit account before copying your firefox profile ?
I'm gonna check if the selenium script still does work, maybe the butsabit site has changed.

**Comment by RosaEidola** [comment]
yeah I logged into my bustabit account before copying the firefox profile. I wonder if something needs to be amended in the selenium script where we run the firefox GUI headless.

**Comment by KylianCadet** [comment]
The issue was from the firefox version pulled in the Dockerfile (the Selenium API couldn't use javascript and the app crashed)
I updated the Dockerfile to fix this.
I also updated bot.py to remove de deprecation warning.
Can you pull the latest version and told me if it works now ? Thanks.

**Comment by RosaEidola** [comment]
Pulled the latest version and your fix works perfectly! Bot currently running with no issues/errors
Thanks again!
