### ISSUE TITLE
Update required for selenium options arg

### ISSUE THREAD

**Issue by RosaEidola** [MageNume/bustabit-bot#9]
Hi,

Hope all is well. Apologies, I appreciate that this is an old repo but are you able to update this to run on newer selenium version as currently it fails.

Many thanks for your time.

**Comment by KylianCadet** [comment]
l locked the selenium version to the latest and modify the script accordingly :)
I am now using the compose plugin of docker, i updated this part in the readme, it should still work with the way you launch the docker-compose file.

**Comment by RosaEidola** [comment]
excellent! 

Works perfectly now, Thanks!
